server:
  port: ":8080"
mysql:
  dsn: "root:12345678@tcp(127.0.0.1:3306)/storydb?charset=utf8mb4&parseTime=True&loc=Local"
ai:
  image_api: "http://ai-image-service/api/generate"
  voice_api: "http://ai-voice-service/api/generate"

redis:
  addr: "127.0.0.1:6379"  
  password: ""            
  db: 0                   

worker:
  addr: "http://127.0.0.1:6000/generate"
  timeout_minutes: 20 